/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author RODRIGO_PC
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        double lar = (double) tela.getWidth();
        double alt = (int) tela.getHeight();
        lar = lar*0.9;
        alt = alt*0.9;
        this.setSize((int)(lar), (int)(alt));
        setLocationRelativeTo(null);
        this.setResizable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_atalho = new javax.swing.JPanel();
        at_ListaProduto = new javax.swing.JButton();
        at_listaOs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Cadastro = new javax.swing.JMenu();
        menu_listaOs = new javax.swing.JMenu();
        menu_ListadeOrdemdeservico = new javax.swing.JMenuItem();
        menu_ImpressaoOs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painel_atalho.setBackground(new java.awt.Color(255, 255, 255));

        at_ListaProduto.setText("LISTA DE PRODUTOS");
        at_ListaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                at_ListaProdutoActionPerformed(evt);
            }
        });

        at_listaOs.setText("IMPRESAO DE ETIQUETA OS");
        at_listaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                at_listaOsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_atalhoLayout = new javax.swing.GroupLayout(painel_atalho);
        painel_atalho.setLayout(painel_atalhoLayout);
        painel_atalhoLayout.setHorizontalGroup(
            painel_atalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_atalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(at_ListaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(at_listaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(836, Short.MAX_VALUE))
        );
        painel_atalhoLayout.setVerticalGroup(
            painel_atalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_atalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(at_ListaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(at_listaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LogoDataSystem.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        menu_Cadastro.setText("CADASTROS");
        jMenuBar1.add(menu_Cadastro);

        menu_listaOs.setText("ORDEM DE SERVICOS");

        menu_ListadeOrdemdeservico.setText("LISTA DE ORDEM ABERTAS");
        menu_ListadeOrdemdeservico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ListadeOrdemdeservicoActionPerformed(evt);
            }
        });
        menu_listaOs.add(menu_ListadeOrdemdeservico);

        menu_ImpressaoOs.setText("IMPRESSAO DE ETIQUETA EQUIPAMENTO");
        menu_ImpressaoOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ImpressaoOsActionPerformed(evt);
            }
        });
        menu_listaOs.add(menu_ImpressaoOs);

        jMenuBar1.add(menu_listaOs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_atalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_atalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1216, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void at_ListaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_at_ListaProdutoActionPerformed

        TelaListadeProdutos telaP = new TelaListadeProdutos();
        telaP.setTitle("Lista de Produtos");
        telaP.setVisible(true);
        
        
    }//GEN-LAST:event_at_ListaProdutoActionPerformed

    private void at_listaOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_at_listaOsActionPerformed
         TelaListaOrdemDeServico telaE = new TelaListaOrdemDeServico();
        telaE.setTitle("Lista de Ordem de Serviços");
        telaE.setVisible(true);
        double lar1 = (double) this.getWidth();
        double alt1 = (int) this.getHeight();
        lar1 = lar1*0.8;
        alt1 = alt1*0.8;
        telaE.setSize((int)(lar1), (int)(alt1));
        telaE.setLocationRelativeTo(null);
        telaE.setResizable(true);
    }//GEN-LAST:event_at_listaOsActionPerformed

    private void menu_ImpressaoOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ImpressaoOsActionPerformed
       TelaImpressaoEtiquetaOs telaE = new TelaImpressaoEtiquetaOs();
        telaE.setTitle("Impressao de Etiqueta");
        telaE.setVisible(true);
        telaE.B_imprimeEtiqueta.setVisible(false);
    }//GEN-LAST:event_menu_ImpressaoOsActionPerformed

    private void menu_ListadeOrdemdeservicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ListadeOrdemdeservicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_ListadeOrdemdeservicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton at_ListaProduto;
    private javax.swing.JButton at_listaOs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu_Cadastro;
    private javax.swing.JMenuItem menu_ImpressaoOs;
    private javax.swing.JMenuItem menu_ListadeOrdemdeservico;
    private javax.swing.JMenu menu_listaOs;
    private javax.swing.JPanel painel_atalho;
    // End of variables declaration//GEN-END:variables
}
