/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Conec;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author RODRIGO_PC
 */
public class TelaImpressaoEtiquetaOs extends javax.swing.JFrame {

    /**
     * Creates new form TelaLiscatagemdeClientes
     */
    public TelaImpressaoEtiquetaOs() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_imprimeEtiqueta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campo_codOs = new javax.swing.JTextField();
        B_pesquisar = new javax.swing.JButton();
        campo_equipamento = new javax.swing.JTextField();
        campo_nomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_data = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campo_CodCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        B_imprimeEtiqueta.setText("IMPRIMIR ETIQUETA");
        B_imprimeEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_imprimeEtiquetaActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de OS");

        campo_codOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_codOsActionPerformed(evt);
            }
        });

        B_pesquisar.setText("Pesquisar");
        B_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pesquisarActionPerformed(evt);
            }
        });

        campo_equipamento.setEditable(false);
        campo_equipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_equipamentoActionPerformed(evt);
            }
        });

        campo_nomeCliente.setEditable(false);
        campo_nomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Equipamento");

        jLabel4.setText("Nome");

        campo_data.setEditable(false);

        jLabel5.setText("Data de Abertura");

        jLabel6.setText("Codigo");

        campo_CodCliente.setEditable(false);
        campo_CodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_CodClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_CodCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(campo_codOs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B_imprimeEtiqueta))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(campo_data, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(campo_codOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_pesquisar)
                        .addComponent(B_imprimeEtiqueta)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_CodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_imprimeEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_imprimeEtiquetaActionPerformed
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            con = Conec.Conectar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaImpressaoEtiquetaOs.class.getName()).log(Level.SEVERE, null, ex);
        }

        String sql = ("select  cabec.idos_oscabecalho as codOS , cabec.codcliente as codcliente,cli.nome as nome,cabec.datachamado as data, cabec.horachamado as hora  , pat.descricao as patri from OS_OSCABECALHO as cabec left join   cliente as cli on cabec.codcliente = cli.codcliente left join  os_ospatrimonoavulso  as pat on   cabec.idos_oscabecalho  =  pat.idos_oscabecalho where cabec.idos_oscabecalho = ? ;");

        try {
            pst = con.prepareStatement(sql);
            int aux = Integer.parseInt(campo_codOs.getText());
            pst.setInt(1, aux);
            rs = pst.executeQuery();
        } catch (SQLException E) {
            JOptionPane.showMessageDialog(null, E);
        }

        try {
            JRResultSetDataSource resultset = new JRResultSetDataSource(rs);

            Map map = null;
            String url = "src\\Relatorios\\etiquetaos.jasper";
            System.out.println(url);
            JasperPrint jasperPrint = JasperFillManager.fillReport(url, map, resultset);
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_B_imprimeEtiquetaActionPerformed

    private void B_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pesquisarActionPerformed
        String temp = campo_codOs.getText();
        if (!(temp.equals(""))) {
            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;

            try {
                con = Conec.Conectar();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaImpressaoEtiquetaOs.class.getName()).log(Level.SEVERE, null, ex);
            }
            String sql = ("select  cabec.idos_oscabecalho as codOS , cabec.codcliente as codcliente,cli.nome as nome,cabec.datachamado as data, cabec.horachamado as hora  , pat.descricao as patri from OS_OSCABECALHO as cabec left join   cliente as cli on cabec.codcliente = cli.codcliente left join  os_ospatrimonoavulso  as pat on   cabec.idos_oscabecalho  =  pat.idos_oscabecalho where cabec.idos_oscabecalho = ? ;");

            try {
                pst = con.prepareStatement(sql);
                int aux = Integer.parseInt(campo_codOs.getText());
                pst.setInt(1, aux);
                rs = pst.executeQuery();

                if (rs.next()) {
                    campo_nomeCliente.setText(rs.getString("nome"));
                    campo_equipamento.setText(rs.getString("patri"));
                    campo_data.setText(rs.getString("data"));
                    campo_CodCliente.setText(rs.getString("codcliente"));
                    B_imprimeEtiqueta.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ORDEM DE SERVIÇO DE NUMERO: " + aux + " NÃO FOI ENCONTRADA", "Aviso", HEIGHT);
                    campo_codOs.setText("");
                }

            } catch (SQLException E) {
                JOptionPane.showMessageDialog(null, E);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "DIGITE UM NUMERO DE ORDEM DE SERVIÇO", "Aviso", HEIGHT);
        }
    }//GEN-LAST:event_B_pesquisarActionPerformed

    private void campo_nomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nomeClienteActionPerformed

    private void campo_codOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_codOsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_codOsActionPerformed

    private void campo_equipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_equipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_equipamentoActionPerformed

    private void campo_CodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_CodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_CodClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaImpressaoEtiquetaOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaImpressaoEtiquetaOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaImpressaoEtiquetaOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaImpressaoEtiquetaOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaImpressaoEtiquetaOs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton B_imprimeEtiqueta;
    private javax.swing.JButton B_pesquisar;
    private javax.swing.JTextField campo_CodCliente;
    private javax.swing.JTextField campo_codOs;
    private javax.swing.JTextField campo_data;
    private javax.swing.JTextField campo_equipamento;
    private javax.swing.JTextField campo_nomeCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
